cookie:
  expiry_days: 0
  key: r3io4mf
  name: let cookie monster eat
credentials:
  usernames:
    bob:
      email: nseriousynot@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: bob
      password: $2b$12$7ykoQ.yVVQKY5alwjm4.0e5psehekycP5nKDz7/DDG1m6TsGbJ5zq
    boba:
      email: bobqwerties@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: boba
      password: hello123
    boby:
      email: nseriouslynoots@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: boby
      password: $2b$12$P6qDRFpg7t2GzZSv7Ef0j.UnpHIWsh1GjD2bBBBd7iFR5Zu1VOX8q
